version: "3"

services:
  guacamole:
    hostname: guacamole
    container_name: guacamole
    image: qualix_guacamole
    depends_on:
      - guacd
    environment:
      - GUACAMOLE_HOME=/opt/guacamole/.guacamole
      - GUACD_HOSTNAME=guacd
      - GUACD_PORT=4822
    ports:
      - ${PORT_8080}:8080
      - ${PORT_8443}:8443
    volumes:
      - files:${GUACAMOLE_HOME}/files
    networks:
      guacnetwork_compose:
    restart: always
  guacd:
    hostname: guacd
    container_name: guacd
    image: qualix_guacd
    environment:
      - GUACD_LOG_LEVEL=debug
    expose:
      - 4822
    ports:
      - 4822:4822
    networks:
      guacnetwork_compose:

networks:
  guacnetwork_compose:
    driver: bridge
volumes:
  files:

